#spring.application.name=FinalExam
#
#debug=true
##spring.jpa.hibernate.ddl-auto=create-drop
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.datasource.url=jdbc:postgresql://localhost:5432/exam
#spring.datasource.username=postgres
#spring.datasource.password=postgres
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.properties.hibernate.show_sql=true
#
#spring.mvc.hiddenmethod.filter.enabled=true

spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/exam
  flyway:
    user: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/exam
    locations: classpath:db/migrations
  jpa:
    properties:
      hibernate:
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
#        format_sql: true
#    hibernate:
#      ddl-auto: create-drop
tg:
  username: ZenTravels_bot
  token: 7141328109:AAFHLngm4hoQvwXvqPHvSGCdcVN2IIAcmLU

